$(document).ready(function(){
		  $("#q1").click(function(){
			$("#a1").slideToggle("fast");
		  });
		  $("#q2").click(function(){
			$("#a2").slideToggle("fast");
		  });
		  $("#q3").click(function(){
			$("#a3").slideToggle("fast");
		  });
		  $("#q4").click(function(){
			$("#a4").slideToggle("fast");
		  });
		  $("#q5").click(function(){
			$("#a5").slideToggle("fast");
		  });
		  $("#q6").click(function(){
			$("#a6").slideToggle("fast");
		  });
		  $("#q7").click(function(){
			$("#a7").slideToggle("fast");
		  });
		  $("#q8").click(function(){
			$("#a8").slideToggle("fast");
		  });
		  $("#q9").click(function(){
			$("#a9").slideToggle("fast");
		  });
		  $("#q10").click(function(){
			$("#a10").slideToggle("fast");
		  });
		  $("#q11").click(function(){
			$("#a11").slideToggle("fast");
		  });
		  $("#q12").click(function(){
			$("#a12").slideToggle("fast");
		  });
		  $("#q13").click(function(){
			$("#a13").slideToggle("fast");
		  });
		  $("#q14").click(function(){
			$("#a14").slideToggle("fast");
		  });
		  $("#q15").click(function(){
			$("#a15").slideToggle("fast");
		  });
		  $("#q16").click(function(){
			$("#a16").slideToggle("fast");
		  });
});