<!DOCTYPE HTML>
<html lang="en">
	<head>
		<title>BoBuy</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="/assets/css/main.css"/>
		<link rel="icon" href="/images/bobuy_newlogo.png">
	</head>
	<body>
		<body class="subpage">

		<!-- Header -->
			<?php require ("/homepages/11/d666590624/htdocs/Website/header.php"); ?>

		<!-- Three -->
			<section id="three" class="wrapper">
				<div class="inner">
					<header class="align-center">
					  <h2>Social Media Manager</h2>
					  <p style="color: black">Hong Kong</p>
					</header>
					<h2 style="color:black"><strong>Description</strong></h2>
					<p style="color:black">BoBuy seeks a motivated, creative, and well, awesome Social Media Manager to help us manage our social content and online community outposts. We’re small, but our plans are big. We need someone who thinks big to be part of them.</p>
					<p style="color:black">The Social Media Manager sits at the intersection of our brand, where our voice, personality, and frameworks meet our community and the channels they go to discover, engage, learn, share, and converse. The SMM will help BoBuy build a “best in class” social experience. You will work across our marketing and communications team to translate our core voice, style, and mission into a social engine, with conversations, campaigns, and visuals that will consistently engage our audience into the marketing &amp; purchase funnel, driving discovery, joy, and advocacy. You will be our resident nerd on all social platforms, including all the ones we don’t know about yet. You are as comfortable filming a quick Instagram story, dashing out a blog post on a trending topic you discovered, or diving into our engagement analytics to understand exactly how much people like beer vs. vodka. You will own our social media management tool and build the infrastructure to distribute content at the right times. You will execute and adapt our social content strategy by monitoring our online listening station and sparking conversation across social networks. You will hunt out great content being generated by our community and leverage it at all the right moments. You get a kick out of analyzing trends and managing KPIs that help to drive our growth. You figure out what the best organizations are doing and you figure out something better</p>
					<h2 style="color:black"><strong>You will:</strong></h2>
					<ul style="color: black">
						<li>Be the eyes and ears and hands of our brand on our social outposts</li>
						<li>Be strategic about the tactics that help our content- and us- get discovered and aids in our acquisition efforts </li>
						<li>Own our user-generated content library and manage distribution of our internal content </li>
						<li>Participate in social media, as yourself and as the brand, on our behalf </li>
						<li>Build an analytical framework behind our social strategy</li>
						<li>Be the steward of our editorial calendar- gathering input, aligning with the creative team, and ensuring we are delivering a relevant and engaging cadence</li>
						<li>Create weekly trend reports that identify key social and consumer trends as input into our content and merchandising process action, origin story of a product, or a customer highlight</li>
					</ul>
					<h2 style="color:black"><strong>You need:</strong></h2>
					<ul style="color: black">
						<li>2-4 years of experience in social media activation- that lifestyle blog you maintained through college and that Instragram account with 10,000 followers? Those count</li>
						<li>An entrepreneurial nature, excited to be part of an aggressive growth environment</li>
						<li>To be a natural content creator with personal use of social media platforms, including Instagram, Snapchat, Facebook, Medium, Pinterest, etc. 
</li>
						<li>A natural interest in the latest ideas and trends in both CPG and for new consumers</li>
						<li>An understanding of basic social media and online marketing concepts that impact natural search traffic and rankings</li>
						<li>To be an idea person who still knows how to execute efficiently and effectively</li>
						<li>An ability to communicate results to management in a fast paced environment</li>
						<li>To be hungry (and not just for snacks)</li>
						<li>An engaging personality that will shine through both on and offline. We like people a little on the cheeky side</li>
					</ul>
					<h2 style="color:black"><strong>You get:</strong></h2>
					<ul style="color: black">
						<li>The chance to be part of a movement</li>
					</ul>
					<h2 style="color:black"><strong>To apply, include the following in your cover letter:</strong></h2>
					<ul style="color: black">
						<li>Links to relevant business and personal social handles</li>
						<li>Describe how you would propel the content through social media to make sure it got traction, including example posts and strategies</li>
					</ul>
					<center><li><a href="/career/job_application" class="button special">Apply Now!</a></li></center>
			  </div>
			</section>
		<!-- Footer -->
			<?php require ("/homepages/11/d666590624/htdocs/Website/footer.php"); ?>

		<!-- Scripts -->
			<script src="/assets/js/jquery.min.js"></script>
			<script src="/assets/js/skel.min.js"></script>
			<script src="/assets/js/util.js"></script>
			<script src="/assets/js/main.js"></script>
			<script>
				(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
				(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
				m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
				})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
				ga('create', 'UA-99902633-1', 'auto');
				ga('send', 'pageview');

				var trackOutboundLink = function(url, isExternal) {
					var params = {};

					if (!isExternal) {
						params.hitCallback = function () {
							document.location = url;
						}
					}
					ga('send', 'event', 'outbound', 'click', url, params);

					return isExternal;
				}
			</script>	
	</body>
</html>